Update CHANGELOG.md for v1.0
camaraproject/OTPValidation pull request #74
Opened 2024-07-12 14:25 UTC by bigludo7

#### What type of PR is this?

Add one of the following kinds:

* documentation

#### What this PR does / why we need it:

Update CHANGELOG.md for v1.0

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for reviewers:

@hdamker as it my 'first' changelog and for a stable release probably good that you check if it what we expect. I leveraged what Dawid did previously.

#### Changelog input

```
 release-note

```

#### Additional documentation 

This section can be blank.

```
docs

```

2024-07-13 15:45 UTC, hdamker commented
@bigludo7 The CHANGELOG.md should be updated as part of the release PR. I suppose you plan to do first the pre-release with the release candidate of v1.0.0. The release title would be r1.1, the API Version 1.0.0-rc.1. The PR should also change the version and base path within the YAML accordingly and add the API Readiness Checklist. For the CHANGELOG entry there is a template available within [CHANGELOG_TEMPLATE.md](https://github.com/camaraproject/ReleaseManagement/blob/main/documentation/CHANGELOG_TEMPLATE.md).

Contentwise: I wouldn't call the stable release a "patch release". It will be just the first stable release. The reference to the changes within v0.5.0 does not help, as there were nothing documented ;-(

I created a "draft release" with GitHub to see the relevant changes since v0.5.0, I suppose the following PRs should be mentioned, but reformulated and sorted into the categories:

----

* Make '+' mandatory for phoneNumber by @bigludo7 in https://github.com/camaraproject/OTPvalidationAPI/pull/50
* Fixed one-time-password-sms.yaml after megalinter check by @bigludo7 in https://github.com/camaraproject/OTPvalidationAPI/pull/53
* Update Authorization and authentication part accordingly to ICM by @bigludo7 in https://github.com/camaraproject/OTPvalidationAPI/pull/65
* Align securitySchemes with ICM by @fernandopradocabrillo in https://github.com/camaraproject/OTPvalidationAPI/pull/68

(plus the ones which are still open)

## New Contributors
* @fernandopradocabrillo made their first contribution in https://github.com/camaraproject/OTPvalidationAPI/pull/37
* @rartych made their first contribution in https://github.com/camaraproject/OTPvalidationAPI/pull/60

**Full Changelog**: https://github.com/camaraproject/OTPvalidationAPI/compare/v0.5.0...r1.1

------

I'm on vacation the next days, but the Release Management team (e.g. Tanja) can help if needed.

2024-07-16 10:40 UTC, bigludo7 commented
Thanks @hdamker 
This is very helpful. I have rename the issue in order to tackle here the release candidate. Once PR #73 solve i will in this PR add the -rc yaml. I will also work here for the readme file.

Hope I'm on the right way

2024-07-19 12:53 UTC, hdamker commented on CHANGELOG.md
> +**OTPvalidationAPI 1.0.0-rc.1 is the first stable version for CAMARA OTP Validation API**
```suggestion
**OTPvalidationAPI 1.0.0-rc.1 is the release candidate for the first stable version of the CAMARA OTP Validation API**
```

2024-07-19 12:54 UTC, hdamker commented on CHANGELOG.md
> +Align securitySchemes with ICM by @fernandopradocabrillo [PR68](https://github.com/camaraproject/OTPvalidationAPI/pull/68)
```suggestion
* Align securitySchemes with ICM by @fernandopradocabrillo [PR68](https://github.com/camaraproject/OTPvalidationAPI/pull/68)
```

2024-07-19 12:59 UTC, hdamker commented on README.md
> +* **The latest available release and version of CAMARA OTPValidaton API is 1.0.0-rc.1 This is the first stable version candidate of the API**. It is suitable for implementors and could be use with cu
I don't that the release candidate should be used already in productive environment - it is a pre-release. Therefore also "latest" is not the right term (for GitHub this is a public release). And to be consistent with the changelog just a proposal:

```suggestion
* **The latest available version of CAMARA OTPValidaton API is 1.0.0-rc.1 This is the release candidate of the first stable version candidate of the API**. The pre-release is suitable for implementors.
```

2024-07-19 13:02 UTC, hdamker commented on documentation/API_documentation/OTPvalidationAPI-Readiness-Checklist.md
> +|  1 | API definition                               |   M   |         M         |    M    |    M   |   Y   | [link](https://github.com/camaraproject/OTPvalidationAPI/blob/main/code/API_definitions/on
My recommendation would to use relative links - they are always fit to the chosen tag.

```suggestion
|  1 | API definition                               |   M   |         M         |    M    |    M   |   Y   | [link](/code/API_definitions/one-time-password-sms.yaml) |

```

2024-07-19 13:02 UTC, hdamker commented on documentation/API_documentation/OTPvalidationAPI-Readiness-Checklist.md
> +|  5 | API documentation                            |   M   |         M         |    M    |    M   |   Y   | Embed documentation into API spec - [link](https://github.com/camaraproject/OTPvalidationA
```suggestion
|  5 | API documentation                            |   M   |         M         |    M    |    M   |   Y   | Embed documentation into API spec - [link](/code/API_definitions/one-time-password-sms.yaml)  |

```

2024-07-19 13:02 UTC, hdamker commented on documentation/API_documentation/OTPvalidationAPI-Readiness-Checklist.md
> +|  6 | User stories                                 |   O   |         O         |    O    |    M   |   N   | [link](https://github.com/camaraproject/OTPvalidationAPI/blob/main/documentation/API_docum
```suggestion
|  6 | User stories                                 |   O   |         O         |    O    |    M   |   N   | [link](/documentation/API_documentation/OTPValidationAPI_User_Story.md) |

```

2024-07-19 13:05 UTC, hdamker commented on documentation/API_documentation/OTPvalidationAPI-Readiness-Checklist.md
> +Checklist for one-time-password-sms api-version in vx
```suggestion
Checklist for one-time-password-sms v1.0.0-rc.1 in r1.1

```

2024-07-19 13:09 UTC, hdamker commented on CHANGELOG.md
> +This version contains significant changes compared to v0.5.0, and it is not backward compatible.
This line might follow directly after line 30.

2024-07-19 13:12 UTC, hdamker requested changes
@bigludo7 See my comments above. Nothing serious, hence I started with single comments.

2024-07-19 14:55 UTC, bigludo7 commented on CHANGELOG.md
> +**OTPvalidationAPI 1.0.0-rc.1 is the first stable version for CAMARA OTP Validation API**
Yes !

2024-07-19 14:56 UTC, bigludo7 commented
> @bigludo7 See my comments above. Nothing serious, hence I started with single comments.

Thank @hdamker - All inserted.

2024-07-20 07:36 UTC, hdamker approved these changes
LGTM

2024-07-24 12:27 UTC, hdamker requested changes
I did another review considering 
a) the proposed renaming of the repository in #75 
b) that the actual API is one-time-password-sms, not "OTP Validation API"

I did not proposed all changes within the generated links ... they will continue to work after the renaming.

2024-07-24 12:27 UTC, hdamker commented on CHANGELOG.md
> +
There is no "OTPvalidationAPI" ...

```suggestion
This release of OTPValidation contains the definition and documentation of
* one-time-password-sms 1.0.0-rc.1
```

2024-07-24 12:27 UTC, hdamker commented on CHANGELOG.md
> +**OTPvalidationAPI 1.0.0-rc.1** is the first release-candidate version for the v1.0.0 of the OTPValidationAPI.
```suggestion
**one-time-password-sms 1.0.0-rc.1** is the first release-candidate version for the v1.0.0 of the one-time-password-sms API.
```

2024-07-24 12:27 UTC, hdamker commented on CHANGELOG.md
> +  - [View it on ReDoc](https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/camaraproject/OTPvalidationAPI/r1.1/code/API_definitions/one-time-password-sms.yaml&nocors)
```suggestion
  - [View it on ReDoc](https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/camaraproject/OTPValidation/r1.1/code/API_definitions/one-time-password-sms.yaml&nocors)
```

2024-07-24 12:27 UTC, hdamker commented on CHANGELOG.md
> +  - [View it on Swagger Editor](https://editor.swagger.io/?url=https://raw.githubusercontent.com/camaraproject/OTPvalidationAPI/r1.1/code/API_definitions/one-time-password-sms.yaml)
```suggestion
  - [View it on Swagger Editor](https://editor.swagger.io/?url=https://raw.githubusercontent.com/camaraproject/OTPValidation/r1.1/code/API_definitions/one-time-password-sms.yaml)
```

2024-07-24 12:27 UTC, hdamker commented on README.md
> +* **The latest available version of CAMARA OTPValidaton API is 1.0.0-rc.1 This is the release candidate of the first stable version candidate of the API**. The pre-release is suitable for implementor
```suggestion
* **The latest pre-release of OTPValidaton is r1.1. The pre-release contains the release candidate of the first stable version of the one-time-password-sms API**. The pre-release is suitable for implementors.
```

2024-07-24 12:27 UTC, hdamker commented on documentation/API_documentation/OTPvalidationAPI-Readiness-Checklist.md
> +| 11 | Change log updated                           |   M   |         M         |    M    |    M   |   N   | [OTPValidationAPI/PR74](https://github.com/camaraproject/OTPvalidationAPI/pull/14) |
It will be the fact when this PR is merged, you don't want to make another PR to change the link ;-)

```suggestion
| 11 | Change log updated                           |   M   |         M         |    M    |    M   |   N   | [link](/CHANGELOG.md) |

```

2024-07-25 06:30 UTC, bigludo7 commented
> I did another review considering a) the proposed renaming of the repository in #75 b) that the actual API is one-time-password-sms, not "OTP Validation API"
> 
> I did not proposed all changes within the generated links ... they will continue to work after the renaming.

Thanks a lot @hdamker for the help !

2024-07-25 11:36 UTC, hdamker approved these changes

2024-07-25 11:40 UTC, hdamker commented
@bigludo7 I approved the changes as they are working as expected (GitHub does not care about upper/lower case in the repository name). But the repository name is now "OTPValidation", not "OTPvalidation" ...

2024-07-25 11:41 UTC, hdamker commented
Please add @camaraproject/release-management_maintainers if ready for final review.

2024-07-26 06:56 UTC, hdamker reviewed
@bigludo7 Very minor comments from the final review done in context of https://github.com/camaraproject/ReleaseManagement/issues/56

2024-07-26 06:56 UTC, hdamker commented on documentation/API_documentation/OTPvalidationAPI-Readiness-Checklist.md
Name of the file should be one-time-password-sms-API-Readiness-Checklist.md

2024-07-26 06:56 UTC, hdamker commented on documentation/API_documentation/OTPvalidationAPI-Readiness-Checklist.md
> +|  7 | Basic API test cases & documentation         |   O   |         M         |    M    |    M   |   N   | [link](code/Test_Definitions/OTPvalidationAPI.feature) |
```suggestion
|  7 | Basic API test cases & documentation         |   O   |         M         |    M    |    M   |   N   | [link](/code/Test_Definitions/OTPvalidationAPI.feature) |

```

2024-07-26 06:56 UTC, hdamker commented on documentation/API_documentation/OTPvalidationAPI-Readiness-Checklist.md
> +|  8 | Enhanced API test cases & documentation      |   O   |         O         |    O    |    M   |   N   | [link](code/Test_Definitions/OTPvalidationAPI.feature) |
```suggestion
|  8 | Enhanced API test cases & documentation      |   O   |         O         |    O    |    M   |   N   | [link](/code/Test_Definitions/OTPvalidationAPI.feature) |

```

2024-07-26 07:36 UTC, bigludo7 commented on documentation/API_documentation/OTPvalidationAPI-Readiness-Checklist.md
done :)

2024-07-26 07:44 UTC, hdamker approved these changes
LGTM from ReleaseManagement view - suppose we are done here. 

@fernandopradocabrillo the PR still needs a codeowner review before it can be merged

2024-07-26 12:20 UTC, fernandopradocabrillo approved these changes
@hdamker sorry for the late review

LGTM

2024-07-31 16:40 UTC, hdamker commented
@fernandopradocabrillo the PR can be merged and the release created. Let me know if you need support here.

2024-08-07 13:25 UTC, hdamker commented
@fernandopradocabrillo there seem to be no additional comments. Can you please merge the PR and create the release?

2024-08-07 15:02 UTC, fernandopradocabrillo commented
> @fernandopradocabrillo there seem to be no additional comments. Can you please merge the PR and create the release?

Sure! Sorry I didn't see the notification

2024-08-07 15:13 UTC, merged